# Generated by Django 4.2.20 on 2025-05-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author_name',
            field=models.CharField(default='default name', max_length=100),
            preserve_default=False,
        ),
    ]
